remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
locale: "en-US"
title: "Refactored Train"
title_separator: "🍭🌈🦄"
description: "My personal project"
url: "https://blaze349.github.io"
baseurl: "/refactored-train"
repository: "blaze349/refactored-train"
search: true
paginate: 10 # amount of posts to show
paginate_path: /page:num/
